### ISSUE TITLE
[Feature]: Support setting custom Stacks API URLs on the bridge

### ISSUE THREAD

**Issue by djordon** [stacks-network/sbtc#1441]
# Feature - Support setting custom Stacks API URLs on the bridge

## 1. Description

It doesn't appear that the bridge is set up to interact with the correct stacks API in local devenv. This was a blocker when trying to test out a local bridge with the sbtc signers on a local devenv.

### 1.1 Context & Purpose

For most local development, we use our command line tools to start deposits or withdrawals. However, we should transition to using the bridge for local devenv testing as much as possible, so that it benefits from more eyes as we approach launching withdrawals.

## 2. Technical Details:

When trying to convert BTC to sBTC using my local bridge, things did not progress past the opening page after connecting my wallet. I think the bridge erred when trying to get the current sbtc supply from the Stacks API using the `Stacks.js` library. That library will default to using the public Stacks APIs (mainnet or testnet) or a local devenv hosted at `http://localhost:3999` for API calls. However, for devenv we want to use the a custom URL that works with docker compose, such as `http://stacks-node:3999` or something like that.

The `Stacks.js` library supports setting the base URL for calls to the Stacks API, you have to set it at the call site. For example, this call here: https://github.com/stacks-network/sbtc-bridge/blob/9b21d4e41f739458b951e1b7e7fb39d6890f6af8/src/actions/get-current-sbtc-supply.ts#L11-L19 will use the custom network, but we need to also set the a client object to specify the API URL.

You can follow the logic by looking here https://github.com/hirosystems/stacks.js/blob/main/packages/network/src/network.ts#L126 and here https://github.com/hirosystems/stacks.js/blob/main/packages/network/src/network.ts#L61-L66. And this was corroborated by this comment on an issue in the library's repo https://github.com/hirosystems/stacks.js/issues/1760#issuecomment-2476713326.

### 2.1 Acceptance Criteria:
   - [ ] We can use the bridge in devenv as a self contained system.

## 3. Related Issues and Pull Requests (optional):

This came up when investigating https://github.com/stacks-network/sbtc/issues/1384. But we should use the bridge more often anyway, so we should fix this.

**Comment by djordon** [comment]
I tried running devenv by modifying the bridge service entry in `docker/docker-compose.yml` with the following environment variable stanza:
```yaml
  sbtc-bridge-website:
    build:
      context: bridge-website
      dockerfile: Dockerfile
    depends_on:
      - stacks-node
      - stacks-api
      - emily-server
      - bitcoin
    ports:
      - "3010:3000"
    profiles:
      - default
    # This part is new
    environment:
      BITCOIND_URL: http://bitcoin:18443
      EMILY_URL: http://emily-server:3031
      MEMPOOL_API_URL: http://mempool-api:8999/api
      PUBLIC_MEMPOOL_URL: http://mempool-api:8999
      BITCOIN_RPC_USER_NAME: devnet
      BITCOIN_RPC_PASSWORD: devnet
      WALLET_NETWORK: sbtcDevenv
      RECLAIM_LOCK_TIME: 7
      SBTC_CONTRACT_DEPLOYER: SN3R84XZYA63QS28932XQF3G1J8R9PC3W76P9CSQS
```
Putting it here to (hopefully) save folks some time.
