### ISSUE TITLE
[sBTC DR] Add logs for sbtc/romeo

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc#180]
When using `./sbtc/up.sh` the logs of sbtc container are empty.
There should be some indications that the engine is up and running or waiting or failed.

**Comment by friedger** [comment]
To see some logs, in `devenet/docker-compose.yml` add for sbtc

```
      RUST_LOG: "romeo=trace"
```
 
like
```
      - miner
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: "romeo=trace"
    volumes:
```
